Repository 2025-databasedesign/frontend, pull requests merged in 2025-05, with the labels that each got.

#1 Implement Navbar, Homepage, Poster(Movie)Info, styling by picocss
  README.md
  VITE-SETUP.md
  index.html
  src/App.tsx
  src/assets/arrow_left_white.png
  src/assets/arrow_right_white.png
  src/assets/grade_15.png
  src/assets/grade_19.png
  src/assets/logo-transparent-bg.png
  src/assets/logo.png
  src/assets/movie1.jpg
  src/assets/star.png
  src/components/Navbar.css
  src/components/Navbar.tsx
  src/components/PosterInfo.css
  src/components/PosterInfo.tsx
  src/css/pico.min.css
  src/index.css
  src/main.tsx
  src/pages/HomePage.css
  src/pages/HomePage.tsx
  src/routes/AppRoutes.ts
  src/routes/MyRoute.tsx
Labels: enhancement, styling, logic, comment

#2 Implement SchedulePage(상영일정 페이지)
  index.html
  package-lock.json
  package.json
  src/assets/cinema_info/mock_cinema.json
  src/assets/schedule/mock_schedule.json
  src/assets/theater_info/mock_theater.json
  src/components/DateSlider.css
  src/components/DateSlider.tsx
  src/components/MovieSelection.css
  src/components/MovieSelection.tsx
  src/components/Navbar.css
  src/components/Navbar.tsx
  src/components/PosterInfo.tsx
  src/components/ScheduleSelectArea.css
  src/components/ScheduleSelectArea.tsx
  src/components/ScheduleSelector.css
  src/components/ScheduleSelector.tsx
  src/components/TheaterSelection.css
  src/components/TheaterSelection.tsx
  src/pages/HomePage.css
  src/pages/HomePage.tsx
  src/pages/SchedulePage.css
  src/pages/SchedulePage.tsx
  src/routes/AppRoutes.ts
  src/routes/MyRoute.tsx
  src/stores/ScheduleRelatedStore.ts
  src/types/scheduleRelatedType.ts
  src/utils/scheduleRelatedUtils.ts
Labels: enhancement, styling, logic

#4 Implement TheaterListPage(상영관목록페이지)
  src/assets/theater_info/mock_seat.json
  src/components/TheaterList/TheaterReview.css
  src/components/TheaterList/TheaterReview.tsx
  src/components/TheaterList/TheaterSeatMap.css
  src/components/TheaterList/TheaterSeatMap.tsx
  src/pages/TheaterListPage.css
  src/pages/TheaterListPage.tsx
Labels: enhancement, styling, logic

#5 Implement ReservationPage(예매페이지)
  src/assets/cinema_info/mock_cinema.json
  src/assets/schedule/mock_schedule.json
  src/components/MovieSelection.css
  src/components/Navbar.css
  src/components/Navbar.tsx
  src/components/ScheduleSelectArea.tsx
  src/components/ScheduleSelector.tsx
  src/components/TheaterSelection.css
  src/pages/HomePage.css
  src/pages/HomePage.tsx
  src/pages/ReservationPage.css
  src/pages/ReservationPage.tsx
  src/routes/AppRoutes.ts
  src/routes/MyRoute.tsx
Labels: enhancement, styling

#7 Implement 결제페이지
  src/components/ScheduleSelectArea/ScheduleSelectArea.tsx
  src/pages/PaymentPage/PaymentPage.css
  src/pages/PaymentPage/PaymentPage.tsx
  src/pages/SeatSelectionPage/SeatSelectionPage.tsx
  src/routes/AppRoutes.ts
  src/routes/MyRoute.tsx
  src/stores/ScheduleRelatedStore.ts
  src/utils/scheduleRelatedUtils.ts
Labels: enhancement, styling, logic
